
ins = '''CREATE TABLE IF NOT EXISTS inspections
               (i_id INTEGER PRIMARY KEY, c_id INTEGER NOT NULL,
               u_id INTEGER NOT NULL, v_id INTEGER NOT NULL, miles INTEGER NOT NULL,
               next_oil INTEGER NOT NULL, next_1 INTEGER, next_2 INTEGER, date TEXT NOT NULL,
               leak_sign INTEGER, leak_sign_t TEXT, leak_sign_b BLOB,
               tires_inflated INTEGER, tires_inflated_t TEXT, tires_inflated_b BLOB,
               windows_clean INTEGER, windows_clean_t TEXT, windows_clean_b BLOB,
               doors_open INTEGER, doors_open_t TEXT, doors_open_b BLOB,
               oil_level INTEGER, oil_level_t TEXT, oil_level_b BLOB,
               coolant_level INTEGER, coolant_level_t TEXT, coolant_level_b BLOB,
               brake_fluid INTEGER, brake_fluid_t TEXT, brake_fluid_b BLOB,
               transmission_fluid INTEGER, transmission_fluid_t TEXT, transmission_fluid_b BLOB,
               steering_fluid INTEGER, steering_fluid_t TEXT, steering_fluid_b BLOB,
               battery_corrosion INTEGER, battery_corrosion_t TEXT, battery_corrosion_b BLOB,
               windshield_fluid INTEGER, windshield_fluid_t TEXT, windshield_fluid_b BLOB,
               hoses INTEGER, hoses_t TEXT, hoses_b BLOB,
               belts INTEGER, belts_t TEXT, belts_b BLOB,
               interior_clean INTEGER, interior_clean_t TEXT, interior_clean_b BLOB,
               rear_compartment INTEGER, rear_compartment_t TEXT, rear_compartment_b BLOB,
               seatbelts INTEGER, seatbelts_t TEXT, seatbelts_b BLOB,
               mirrors INTEGER, mirrors_t TEXT, mirrors_b BLOB,
               brakes INTEGER, brakes_t TEXT, brakes_b BLOB,
               heater INTEGER, heater_t TEXT, heater_b BLOB,
               ac INTEGER, ac_t TEXT, ac_b BLOB,
               fuel INTEGER, fuel_t TEXT, fuel_b BLOB,
               warning_lights INTEGER, warning_lights_t TEXT, warning_lights_b BLOB,
               door_locks INTEGER, door_locks_t TEXT, door_locks_b BLOB,
               seats INTEGER, seats_t TEXT, seats_b BLOB,
               windows INTEGER, windows_t TEXT, windows_b BLOB,
               fleft_turn INTEGER, fleft_turn_t TEXT, fleft_turn_b BLOB,
               fright_turn INTEGER, fright_turn_t TEXT, fright_turn_b BLOB,
               rleft_turn INTEGER, rleft_turn_t TEXT, rleft_turn_b BLOB,
               rright_turn INTEGER, rright_turn_t TEXT, rright_turn_b BLOB,
               high_beam INTEGER, high_beam_t TEXT, high_beam_b BLOB,
               low_beams INTEGER, low_beams_t TEXT, low_beams_b BLOB,
               reverse_lights INTEGER, reverse_lights_t TEXT, reverse_lights_b BLOB,
               emergency_flashers INTEGER, emergency_flashers_t TEXT, emergency_flashers_b BLOB,
               trailer_connection INTEGER, trailer_connection_t TEXT, trailer_connection_b BLOB,
               harness INTEGER, harness_t TEXT, harness_b BLOB,
               glasses INTEGER, glasses_t TEXT, glasses_b BLOB,
               face_shield INTEGER, face_shield_t TEXT, face_shield_b BLOB,
               hard_hat INTEGER, hard_hat_t TEXT, hard_hat_b BLOB,
               gloves INTEGER, gloves_t TEXT, gloves_b BLOB,
               sleeves INTEGER, sleeves_t TEXT, sleeves_b BLOB,
               shoes INTEGER, shoes_t TEXT, shoes_b BLOB,
               ladders_racks INTEGER, ladders_racks_t TEXT, ladders_racks_b BLOB,
               boom_control INTEGER, boom_control_t TEXT, boom_control_b BLOB,
               hose_leaks INTEGER, hose_leaks_t TEXT, hose_leaks_b BLOB,
               hydraulics_leaks INTEGER, hydraulics_leaks_t TEXT, hydraulics_leaks_b BLOB,
               basket INTEGER, basket_t TEXT, basket_b BLOB,
               extra1 INTEGER, extra1_t TEXT, extra1_b BLOB,
               extra2 INTEGER, extra2_t TEXT, extra2_b BLOB,
               extra3 INTEGER, extra3_t TEXT, extra3_b BLOB,
               extra4 INTEGER, extra4_t TEXT, extra4_b BLOB,
               extra5 INTEGER, extra5_t TEXT, extra5_b BLOB,
               extra6 INTEGER, extra6_t TEXT, extra6_b BLOB,
               extra7 INTEGER, extra7_t TEXT, extra7_b BLOB,
               extra8 INTEGER, extra8_t TEXT, extra8_b BLOB,
               extra9 INTEGER, extra9_t TEXT, extra9_b BLOB,
               extra10 INTEGER, extra10_t TEXT, extra10_b BLOB,
               extra11 INTEGER, extra11_t TEXT, extra11_b BLOB,
               extra12 INTEGER, extra12_t TEXT, extra12_b BLOB,
               extra13 INTEGER, extra13_t TEXT, extra13_b BLOB,
               extra14 INTEGER, extra14_t TEXT, extra14_b BLOB,
               extra15 INTEGER, extra15_t TEXT, extra15_b BLOB,
               extra16 INTEGER, extra16_t TEXT, extra16_b BLOB,
               extra17 INTEGER, extra17_t TEXT, extra17_b BLOB,
               extra18 INTEGER, extra18_t TEXT, extra18_b BLOB,
               extra19 INTEGER, extra19_t TEXT, extra19_b BLOB,
               extra20 INTEGER, extra20_t TEXT, extra20_b BLOB,
               extra21 INTEGER, extra21_t TEXT, extra21_b BLOB,
               extra22 INTEGER, extra22_t TEXT, extra22_b BLOB,
               extra23 INTEGER, extra23_t TEXT, extra23_b BLOB,
               extra24 INTEGER, extra24_t TEXT, extra24_b BLOB,
               extra25 INTEGER, extra25_t TEXT, extra25_b BLOB,
               extra26 INTEGER, extra26_t TEXT, extra26_b BLOB,
               extra27 INTEGER, extra27_t TEXT, extra27_b BLOB,
               extra28 INTEGER, extra28_t TEXT, extra28_b BLOB,
               extra29 INTEGER, extra29_t TEXT, extra29_b BLOB,
               extra30 INTEGER, extra30_t TEXT, extra30_b BLOB,
               extra31 INTEGER, extra31_t TEXT, extra31_b BLOB,
               extra32 INTEGER, extra32_t TEXT, extra32_b BLOB,
               extra33 INTEGER, extra33_t TEXT, extra33_b BLOB,
               extra34 INTEGER, extra34_t TEXT, extra34_b BLOB,
               extra35 INTEGER, extra35_t TEXT, extra35_b BLOB,
               extra36 INTEGER, extra36_t TEXT, extra36_b BLOB,
               extra37 INTEGER, extra37_t TEXT, extra37_b BLOB,
               extra38 INTEGER, extra38_t TEXT, extra38_b BLOB,
               extra39 INTEGER, extra39_t TEXT, extra39_b BLOB,
               extra40 INTEGER, extra40_t TEXT, extra40_b BLOB,
               FOREIGN KEY (c_id) REFERENCES companys (id) ON DELETE CASCADE
               ON UPDATE NO ACTION, FOREIGN KEY (u_id) REFERENCES users (u_id) ON DELETE NO ACTION
               ON UPDATE NO ACTION, FOREIGN KEY (v_id) REFERENCES users (v_id) ON DELETE NO ACTION
               ON UPDATE NO ACTION)'''

c1 = [["leak_sign", "leak_sign_t", "leak_sign_b", "There are no signs of leaks under the vehicle"],
        ["tires_inflated", "tires_inflated_t", "tires_inflated_b", "Tires are inflated to proper PSI"],
        ["windows_clean", "windows_clean_t", "windows_clean_b", "Windows and Mirrors are clean and they don't have cracks"],
        ["doors_open", "doors_open_t", "doors_open_b", "Doors open a close properly"],
        ["oil_level", "oil_level_t", "oil_level_b", "Oil level is OK"],
        ["coolant_level", "coolant_level_t", "coolant_level_b", "Coolant level is OK"],
        ["brake_fluid", "brake_fluid_t", "brake_fluid_b", "Brake fluid level is OK"],
        ["transmission_fluid", "transmission_fluid_t", "transmission_fluid_b", "Transmission fluid level is OK"],
        ["steering_fluid", "steering_fluid_t", "steering_fluid_b", "Power steering fluid level is OK"],
        ["battery_corrosion", "battery_corrosion_t", "battery_corrosion_b", "There is no corrosion on the battery(s)"],
        ["windshield_fluid", "windshield_fluid_t", "windshield_fluid_b", "Windshield washer fluid level is OK"],
        ["hoses", "hoses_t", "hoses_b", "No hoses dripping, cracked or leaking"],
        ["belts", "belts_t", "belts_b", "No Frayed or cracked belts"],
        ["interior_clean", "interior_clean_t", "interior_clean_b", "Clean Interior?"],
        ["rear_compartment", "rear_compartment_t", "rear_compartment_b", "Clean and free of debris rear compartment/bucket area"],
        ["seatbelts", "seatbelts_t", "seatbelts_b", "Seat belts in good condition"],
        ["mirrors", "mirrors_t", "mirrors_b", "Mirrors adjust properly"],
        ["brakes", "brakes_t", "brakes_b", "Brakes work correctly"],
        ["heater", "heater_t", "heater_b", "Heater works correctly"],
        ["ac", "ac_t", "ac_b", "A/C cools down properly"],
        ["fuel", "fuel_t", "fuel_b", "There is adequate fuel on the vehicle"],
        ["warning_lights", "warning_lights_t", "warning_lights_b", "There are no warning light on"],
        ["door_locks", "door_locks_t", "door_locks_b", "Doors lock properly"],
        ["seats", "seats_t", "seats_b", "Seats in good condition and move freely"],
        ["windows", "windows_t", "windows_b", "Windows open/close properly"],
        ["fleft_turn", "fleft_turn_t", "fleft_turn_b", "Front left turn signal operational"],
        ["fright_turn", "fright_turn_t", "fright_turn_b", "Front right turn signal operational"],
        ["rleft_turn", "rleft_turn_t", "rleft_turn_b", "Rear left turn signal operational"],
        ["rright_turn", "rright_turn_t", "rright_turn_b", "Rear right turn signal operational"],
        ["high_beam", "high_beam_t", "high_beam_b", "High beams operational"],
        ["low_beams", "low_beams_t", "low_beams_b", "Low beams operational"],
        ["reverse_lights", "reverse_lights_t", "reverse_lights_b", "Reverse lights operational"],
        ["emergency_flashers", "emergency_flashers_t", "emergency_flashers_b", "Emergency flashers operational"],
        ["trailer_connection", "trailer_connection_t", "trailer_connection_b", "Trailer connection (if equiped) operational"],
        ["harness", "harness_t", "harness_b", "Harness"],
        ["glasses", "glasses_t", "glasses_b", "Safety Glasses"],
        ["face_shield", "face_shield_t", "face_shield_b", "Face shield"],
        ["hard_hat", "hard_hat_t", "hard_hat_b", "Hard hat"],
        ["gloves", "gloves_t", "gloves_b", "Insulating gloves"],
        ["sleeves", "sleeves_t", "sleeves_b", "Insulating sleeves"],
        ["shoes", "shoes_t", "shoes_b", "Safety shoes"],
        ["ladders_racks", "ladders_racks_t", "ladders_racks_b", "Ladders and rack in good condition"],
        ["boom_control", "boom_control_t", "boom_control_b", "Boom controls operationg properly"],
        ["hose_leaks", "hose_leaks_t", "hose_leaks_b", "No leaks or cracks on hydraulic hoses"],
        ["hydraulics_leaks", "hydraulics_leaks_t", "hydraulics_leaks_b", "No oil leaks from hydraulics"],
        ["basket", "basket_t", "basket_b", "Basket is clean"],
        ["extra1", "extra1_t", "extra1_b", "No mechanical failure"],
        ["extra2", "extra2_t", "extra2_b", "Any other external or internal damage/failure to comment"]]
