

CREATE TABLE IF NOT EXISTS companys
               (id INTEGER PRIMARY KEY, name TEXT UNIQUE NOT NULL,
               show_name TEXT, owner TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS users
               (u_id INTEGER PRIMARY KEY, c_id INTEGER NOT NULL,
               username TEXT NOT NULL, email TEXT NOT NULL,
               hash TEXT NOT NULL, role TEXT NOT NULL, FOREIGN KEY (c_id)
               REFERENCES companys (id) ON DELETE CASCADE ON UPDATE NO ACTION);
CREATE TABLE IF NOT EXISTS vehicles
               (v_id INTEGER PRIMARY KEY, c_id INTEGER NOT NULL,
               make TEXT NOT NULL, model TEXT NOT NULL,
               year TEXT NOT NULL, number TEXT NOT NULL, vin TEXT UNIQUE NOT NULL,
               tag TEXT, FOREIGN KEY (c_id) REFERENCES companys (id) ON DELETE CASCADE
               ON UPDATE NO ACTION);
CREATE TABLE IF NOT EXISTS inspections
               (i_id INTEGER PRIMARY KEY, c_id INTEGER NOT NULL,
               u_id INTEGER NOT NULL, v_id INTEGER NOT NULL, miles INTEGER NOT NULL,
               next_oil INTEGER NOT NULL, next_1 INTEGER, next_2 INTEGER, date TEXT NOT NULL,
               leak_sign INTEGER, leak_sign_t TEXT, leak_sign_b BLOB,
               tires_inflated INTEGER, tires_inflated_t TEXT, tires_inflated_b BLOB,
               windows_clean INTEGER, windows_clean_t TEXT, windows_clean_b BLOB,
               doors_open INTEGER, doors_open_t TEXT, doors_open_b BLOB,
               oil_level INTEGER, oil_level_t TEXT, oil_level_b BLOB,
               coolant_level INTEGER, coolant_level_t TEXT, coolant_level_b BLOB,
               brake_fluid INTEGER, brake_fluid_t TEXT, brake_fluid_b BLOB,
               transmission_fluid INTEGER, transmission_fluid_t TEXT, transmission_fluid_b BLOB,
               steering_fluid INTEGER, steering_fluid_t TEXT, steering_fluid_b BLOB,
               battery_corrosion INTEGER, battery_corrosion_t TEXT, battery_corrosion_b BLOB,
               windshield_fluid INTEGER, windshield_fluid_t TEXT, windshield_fluid_b BLOB,
               hoses INTEGER, hoses_t TEXT, hoses_b BLOB,
               belts INTEGER, belts_t TEXT, belts_b BLOB,
               interior_clean INTEGER, interior_clean_t TEXT, interior_clean_b BLOB,
               rear_compartment INTEGER, rear_compartment_t TEXT, rear_compartment_b BLOB,
               seatbelts INTEGER, seatbelts_t TEXT, seatbelts_b BLOB,
               mirrors INTEGER, mirrors_t TEXT, mirrors_b BLOB,
               brakes INTEGER, brakes_t TEXT, brakes_b BLOB,
               heater INTEGER, heater_t TEXT, heater_b BLOB,
               ac INTEGER, ac_t TEXT, ac_b BLOB,
               fuel INTEGER, fuel_t TEXT, fuel_b BLOB,
               warning_lights INTEGER, warning_lights_t TEXT, warning_lights_b BLOB,
               door_locks INTEGER, door_locks_t TEXT, door_locks_b BLOB,
               seats INTEGER, seats_t TEXT, seats_b BLOB,
               windows INTEGER, windows_t TEXT, windows_b BLOB,
               fleft_turn INTEGER, fleft_turn_t TEXT, fleft_turn_b BLOB,
               fright_turn INTEGER, fright_turn_t TEXT, fright_turn_b BLOB,
               rleft_turn INTEGER, rleft_turn_t TEXT, rleft_turn_b BLOB,
               rright_turn INTEGER, rright_turn_t TEXT, rright_turn_b BLOB,
               high_beam INTEGER, high_beam_t TEXT, high_beam_b BLOB,
               low_beams INTEGER, low_beams_t TEXT, low_beams_b BLOB,
               reverse_lights INTEGER, reverse_lights_t TEXT, reverse_lights_b BLOB,
               emergency_flashers INTEGER, emergency_flashers_t TEXT, emergency_flashers_b BLOB,
               trailer_connection INTEGER, trailer_connection_t TEXT, trailer_connection_b BLOB,
               harness INTEGER, harness_t TEXT, harness_b BLOB,
               glasses INTEGER, glasses_t TEXT, glasses_b BLOB,
               face_shield INTEGER, face_shield_t TEXT, face_shield_b BLOB,
               hard_hat INTEGER, hard_hat_t TEXT, hard_hat_b BLOB,
               gloves INTEGER, gloves_t TEXT, gloves_b BLOB,
               sleeves INTEGER, sleeves_t TEXT, sleeves_b BLOB,
               shoes INTEGER, shoes_t TEXT, shoes_b BLOB,
               ladders_racks INTEGER, ladders_racks_t TEXT, ladders_racks_b BLOB,
               boom_control INTEGER, boom_control_t TEXT, boom_control_b BLOB,
               hose_leaks INTEGER, hose_leaks_t TEXT, hose_leaks_b BLOB,
               hydraulics_leaks INTEGER, hydraulics_leaks_t TEXT, hydraulics_leaks_b BLOB,
               basket INTEGER, basket_t TEXT, basket_b BLOB,
               extra1 INTEGER, extra1_t TEXT, extra1_b BLOB,
               extra2 INTEGER, extra2_t TEXT, extra2_b BLOB,
               extra3 INTEGER, extra3_t TEXT, extra3_b BLOB,
               extra4 INTEGER, extra4_t TEXT, extra4_b BLOB,
               extra5 INTEGER, extra5_t TEXT, extra5_b BLOB,
               extra6 INTEGER, extra6_t TEXT, extra6_b BLOB,
               extra7 INTEGER, extra7_t TEXT, extra7_b BLOB,
               extra8 INTEGER, extra8_t TEXT, extra8_b BLOB,
               extra9 INTEGER, extra9_t TEXT, extra9_b BLOB,
               extra10 INTEGER, extra10_t TEXT, extra10_b BLOB,
               extra11 INTEGER, extra11_t TEXT, extra11_b BLOB,
               extra12 INTEGER, extra12_t TEXT, extra12_b BLOB,
               extra13 INTEGER, extra13_t TEXT, extra13_b BLOB,
               extra14 INTEGER, extra14_t TEXT, extra14_b BLOB,
               extra15 INTEGER, extra15_t TEXT, extra15_b BLOB,
               extra16 INTEGER, extra16_t TEXT, extra16_b BLOB,
               extra17 INTEGER, extra17_t TEXT, extra17_b BLOB,
               extra18 INTEGER, extra18_t TEXT, extra18_b BLOB,
               extra19 INTEGER, extra19_t TEXT, extra19_b BLOB,
               extra20 INTEGER, extra20_t TEXT, extra20_b BLOB,
               extra21 INTEGER, extra21_t TEXT, extra21_b BLOB,
               extra22 INTEGER, extra22_t TEXT, extra22_b BLOB,
               extra23 INTEGER, extra23_t TEXT, extra23_b BLOB,
               extra24 INTEGER, extra24_t TEXT, extra24_b BLOB,
               extra25 INTEGER, extra25_t TEXT, extra25_b BLOB,
               extra26 INTEGER, extra26_t TEXT, extra26_b BLOB,
               extra27 INTEGER, extra27_t TEXT, extra27_b BLOB,
               extra28 INTEGER, extra28_t TEXT, extra28_b BLOB,
               extra29 INTEGER, extra29_t TEXT, extra29_b BLOB,
               extra30 INTEGER, extra30_t TEXT, extra30_b BLOB,
               extra31 INTEGER, extra31_t TEXT, extra31_b BLOB,
               extra32 INTEGER, extra32_t TEXT, extra32_b BLOB,
               extra33 INTEGER, extra33_t TEXT, extra33_b BLOB,
               extra34 INTEGER, extra34_t TEXT, extra34_b BLOB,
               extra35 INTEGER, extra35_t TEXT, extra35_b BLOB,
               extra36 INTEGER, extra36_t TEXT, extra36_b BLOB,
               extra37 INTEGER, extra37_t TEXT, extra37_b BLOB,
               extra38 INTEGER, extra38_t TEXT, extra38_b BLOB,
               extra39 INTEGER, extra39_t TEXT, extra39_b BLOB,
               extra40 INTEGER, extra40_t TEXT, extra40_b BLOB,
               FOREIGN KEY (c_id) REFERENCES companys (id) ON DELETE CASCADE
               ON UPDATE NO ACTION, FOREIGN KEY (u_id) REFERENCES users (u_id) ON DELETE NO ACTION
               ON UPDATE NO ACTION, FOREIGN KEY (v_id) REFERENCES vehicles (v_id) ON DELETE CASCADE
               ON UPDATE NO ACTION);